# -*- coding: utf-8 -*-
"""CGIPLab07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ule5aFTR4wI_5Ll6e7y3Exo4Clkw_O-z
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load image (use any image path)
img = cv2.imread("vikas.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Function: Window to Viewport Transformation
def window_to_viewport(img, wxmin, wymin, wxmax, wymax,
                       vxmin, vymin, vxmax, vymax):

    # Extract window
    window = img[wymin:wymax, wxmin:wxmax]

    # Compute scaling factors
    sx = (vxmax - vxmin) / (wxmax - wxmin)
    sy = (vymax - vymin) / (wymax - wymin)

    # Resize window
    new_width = int(window.shape[1] * sx)
    new_height = int(window.shape[0] * sy)
    resized = cv2.resize(window, (new_width, new_height))

    # Create blank canvas
    canvas = img.copy()

    # Place resized window into viewport
    canvas[vymin:vymin+new_height, vxmin:vxmin+new_width] = resized

    return canvas, sx, sy

# Helper to display
def show(title, image):
    plt.figure()
    plt.imshow(image)
    plt.title(title)
    plt.axis("off")
    plt.show()

# -----------------------------
# Task 1: Basic Mapping
# -----------------------------
res1, sx1, sy1 = window_to_viewport(img,
                                    100, 100, 300, 300,
                                    400, 100, 600, 300)
show("Task 1: Basic Mapping", res1)

# -----------------------------
# Task 2: Same Size (No Scaling)
# -----------------------------
res2, sx2, sy2 = window_to_viewport(img,
                                    100, 100, 300, 300,
                                    400, 100, 600, 300)
show("Task 2: Same Size", res2)

# -----------------------------
# Task 3: Viewport Larger (Upscaling)
# -----------------------------
res3, sx3, sy3 = window_to_viewport(img,
                                    100, 100, 200, 200,
                                    350, 50, 650, 350)
show("Task 3: Upscaling", res3)

# -----------------------------
# Task 4: Viewport Smaller (Downscaling)
# -----------------------------
res4, sx4, sy4 = window_to_viewport(img,
                                    50, 50, 350, 350,
                                    400, 100, 550, 250)
show("Task 4: Downscaling", res4)

# -----------------------------
# Task 5: Different Aspect Ratio
# -----------------------------
res5, sx5, sy5 = window_to_viewport(img,
                                    100, 100, 300, 200,
                                    400, 100, 700, 400)
show("Task 5: Aspect Ratio Change", res5)

# -----------------------------
# Task 6: Comparison Output
# -----------------------------
print("Task 2 (Same size): Sx =", sx2, "Sy =", sy2, "→ No scaling")
print("Task 3 (Upscaling): Sx =", sx3, "Sy =", sy3, "→ Enlarged")
print("Task 4 (Downscaling): Sx =", sx4, "Sy =", sy4, "→ Reduced")